name: Build Render Package

on:
  push:
    paths:
      - 'packages/render/**'
      - '.github/workflows/build-render.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm --filter @maily-to/render test
        
      - name: Build render package
        run: pnpm --filter @maily-to/render build
        
      - name: Commit and push dist
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add packages/render/dist -f
          git commit -m "chore: update dist files [skip ci]" || echo "No changes to commit"
          git push
