name: Build Core Package

on:
  push:
    tags:
      - 'v*'
    paths:
      - 'packages/core/**'
      - '.github/workflows/build-core.yml'
  pull_request:
    paths:
      - 'packages/core/**'
      - '.github/workflows/build-core.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm --filter @maily-to/core test
        
      - name: Build core package
        run: pnpm --filter @maily-to/core build

      - name: Create release branch and commit dist
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b release/${{ github.ref_name }}
          git add packages/core/dist -f
          git commit -m "chore: add dist files for ${{ github.ref_name }} [skip ci]" || echo "No changes to commit"
          git push origin release/${{ github.ref_name }}
